version: '3'
services:
  rss_news_aggregator_test:
    image: rss_news_aggregator_test:latest
    container_name: rss_news_aggregator_test
    restart: unless-stopped
    ports:
      - "*****:*****"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - ./wwwroot:/app/wwwroot
    networks:
      - prod

networks:
  test:
    external:
      name: test